// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKifmDyC7YsRuVPWjvfcRCOqf7nEbs2bc',
    appId: '1:1029830734152:web:78f4bc524e5a89e52dc37d',
    messagingSenderId: '1029830734152',
    projectId: 'myproject-72fa1',
    authDomain: 'myproject-72fa1.firebaseapp.com',
    storageBucket: 'myproject-72fa1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6MldLLuXD2Aq3pCS1ifRtjQCBRoCKRs',
    appId: '1:1029830734152:android:849916351d621e162dc37d',
    messagingSenderId: '1029830734152',
    projectId: 'myproject-72fa1',
    storageBucket: 'myproject-72fa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI568JzhSP3_FwBlGycg8T5Zc_8uSUBFo',
    appId: '1:1029830734152:ios:7b5605bc8c0513b32dc37d',
    messagingSenderId: '1029830734152',
    projectId: 'myproject-72fa1',
    storageBucket: 'myproject-72fa1.firebasestorage.app',
    iosBundleId: 'com.example.renoveProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI568JzhSP3_FwBlGycg8T5Zc_8uSUBFo',
    appId: '1:1029830734152:ios:7b5605bc8c0513b32dc37d',
    messagingSenderId: '1029830734152',
    projectId: 'myproject-72fa1',
    storageBucket: 'myproject-72fa1.firebasestorage.app',
    iosBundleId: 'com.example.renoveProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKifmDyC7YsRuVPWjvfcRCOqf7nEbs2bc',
    appId: '1:1029830734152:web:2f9d54d40c3d9dcf2dc37d',
    messagingSenderId: '1029830734152',
    projectId: 'myproject-72fa1',
    authDomain: 'myproject-72fa1.firebaseapp.com',
    storageBucket: 'myproject-72fa1.firebasestorage.app',
  );
}
